### PR TITLE
Add more failing tests of rest element reassignment.

### PR DESCRIPTION
**Pull request by benjamn**
This is a pull request onto your pull request https://github.com/babel/babel/pull/3249. If you merge this PR, that PR should be automatically updated. Fingers crossed!

I expect the new tests to fail, because they contain additional examples of member expressions that can't be replaced with conditional expressions.

### CODE REVIEW

**Comment by vhf** [comment]
That's great @benjamn. Might be a bit easier to fix if could you provide expected results for these tests (if you have an opinion about what it should be transpiled to of course, no pressure!).

**Comment by benjamn** [comment]
This is just a guess, so you should probably prefer the real output if it looks reasonable:

``` js
function swap() {
  for (var _len9 = arguments.length, rest = Array(_len9), _key9 = 0; _key9 < _len9; _key9++) {
    rest[_key9] = arguments[_key9];
  }

  [rest[0], rest[1]] = [rest[1], rest[0]];
}

function x() {
  for (var _len10 = arguments.length, rest = Array(_len10), _key10 = 0; _key10 < _len10; _key10++) {
    rest[_key10] = arguments[_key10];
  }

  for (rest[0] in this) foo(rest[0]);
}
```

I'll update my PR.

**Comment by vhf** [comment]
Thanks!

I fixed `swap` (rest.js l.66, add `&& !grandparentPath.isArrayExpression()`), working on `x()` now. I'll PR this repo when I'm done.

[EDIT]: forIn fixed as well.

**Comment by benjamn** [comment]
I think `swap` may be a specific instance of a more general problem: when the `MemberExpression` is used as an `LVal` (that is, something that gets updated), it can't be replaced with an arbitrary `Expression`. So I'm kind of hoping for a more general solution. I'll try to think of some more test cases.

**Comment by vhf** [comment]
Yep, that's what I noticed with the previous fix for ArrayExpressions. I first added another clause for ForInExpressions and noticed I could replace them with `isLVal`.

After l.66, add `!grandparentPath.isLVal()` instead.

**Comment by benjamn** [comment]
Here are some even nastier cases:

``` js
function inc (...rest) {
  ++rest[0];
}

function dec (...rest) {
  --rest[0];
}

function method (...rest) {
  rest[0]();
}
```

I'll update the other PR to include these as well, but I think this bug deserves more discussion, because it's pretty tricky to tell when it's safe to replace a `MemberExpression` with an arbitrary `Expression`.

**Comment by vhf** [comment]
``` js
function method (...rest) {
  rest[0]();
}
```

is already safely transformed.

``` js
function inc (...rest) {
  ++rest[0];
}

function dec (...rest) {
  --rest[0];
}
```

These are just missing some parens around `loadRest`.

**Comment by benjamn** [comment]
I have to disagree with both claims.

The `method` function is not safely transformed, because the `this` value in the method call will be `undefined`, when it should be the `rest` object:

``` js
(arguments.length <= 0 ? undefined : arguments[0])()
```

It's similar to the difference between `obj.method(x)` and `(0,obj.method)(x)`, if you know that trick.

The `newExp` function that I added seems to be safely transformed, after all, but I think it's still worth keeping as a test.

The problem with the `++` and `--` cases is more than just missing parentheses, because this code doesn't actually update anything when there are parentheses:

``` js
++(arguments.length <= 0 ? undefined : arguments[0])
--(arguments.length <= 0 ? undefined : arguments[0])
```

Again, I think the fundamental issue here is that the ternary `ConditionalExpression` is not an updatable/assignable `LVal`, whereas the `rest[0]` expression is. I wish I knew how to capture that check in a simple, general way.

**Comment by vhf** [comment]
Right, thanks for the clarification. :+1:

**Comment by jmm** [comment]
Thank you both @benjamn and @vhf for the effort on this!

Thanks @benjamn for identifying all of these failure cases, this is great! I think all of these, at least as represented in these fixtures, can be cured. Here is a rough draft WIP building on this PR: https://github.com/benjamn/babel/compare/rest-assign-el...jmm:more-rest-deopt. I still have to check out the `isLVal()` angle you two were discussing to see if that can collapse some of these more specific tests without clobbering legit optimizations.

@vhf if I end up duplicating work that you did that fixes some of these cases let's make sure your commit(s) for that stuff end up in here. Sounds like maybe you already had the array destructuring and for-in cases handled, and collapsed via LVal? In that case we can add what I've come up with for the other cases.

You mentioned `ArrayExpression` -- I might be trying to do this too quick, and haven't seen your actual code of course, but I'm thinking that's not the right solution? I think it might seem like it's fixing it because there are refs to the rest param in an `ArrayExpression` on the RHS in the fixture, but as you can see in my WIP I'm testing for `ArrayPattern` via `isPattern()`. But if you moved on to using `isLVal`  perhaps that takes care of it.

Do you have something you can push, even a rough draft?

Thanks!

**Comment by vhf** [comment]
That's great news @jmm :+1: 

I will not have time to work on this before ~a week, so I quickly commited & pushed what I had last week: https://github.com/vhf/babel/commit/5a1144c3bf0e67f1c72e0d7ea7178cb19b3a3f11 , it's really not much but it does the trick (this commit comes with fixtures and passes the tests as far as I remember).

Please feel free to take what you like from it, don't worry about the commit it's all yours now!

**Comment by jmm** [comment]
@vhf Awesome, thanks! I'll take a look.

**Comment by jmm** [comment]
These are all ok with parens, right?:

``` js
(arguments.length <= 0 ? undefined : arguments[0]) in x;
for ((arguments.length <= 0 ? undefined : arguments[0]) in x);
for ((arguments.length <= 0 ? undefined : arguments[0]) of x);
```

**Comment by benjamn** [comment]
This one is fine:

``` js
(arguments.length <= 0 ? undefined : arguments[0]) in x;
```

But these seem to be parse errors?

``` js
for ((arguments.length <= 0 ? undefined : arguments[0]) in x);
for ((arguments.length <= 0 ? undefined : arguments[0]) of x);
```

The left hand side of the `for` loop head needs to be an assignable LVal, I think. In my Node 4 shell I get `ReferenceError: Invalid left-hand side in for-loop`.

**Comment by jmm** [comment]
Oh, d'oh! Yeah, of course you're right. I was missing the forest for the trees here. I was trying to skim the grammar quick without thinking it through or checking the static semantics.

> It is a Syntax Error if `IsValidSimpleAssignmentTarget` of `LeftHandSideExpression` is false.

EDIT: actually, I'm not sure right this second if it's that one or the next one. One or the other though. http://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements-static-semantics-early-errors

EDIT: also it wouldn't have mattered anyway because we can't try to assign to `undefined` and I think we want to avoid any assignments to `arguments` to avoid engine deopt.

Thanks @benjamn!

**Comment by jmm** [comment]
Again, thank you for this. This commit is now incorporated into https://github.com/babel/babel/pull/3375, so closing this.

**Pull request closed without merging**
